# Generated by Django 3.2.7 on 2021-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('v_email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
